server {
    listen       8000;
    server_name  localhost;

    root  /path/to/orbis/server/public;

    location / {
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-cache";
    }

    location /api/ {
        proxy_pass         http://127.0.0.1:8001;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
    }

    location /files/ {
        auth_request /auth;
        alias /path/to/orbis/server/private/;
        add_header Cache-Control "no-store";
        etag off;
    }

    location = /auth {
        internal;
        proxy_pass         http://127.0.0.1:8001/api/auth;
        proxy_set_header   Host $host;
        proxy_set_header   Cookie $http_cookie;
        proxy_set_header   Content-Length "";
        proxy_pass_request_body off;
    }

    access_log  /var/log/nginx/orbis-access.log;
    error_log   /var/log/nginx/orbis-error.log;
}

# Replace 'root' and 'location /files/ alias' paths with the proper values, then:
# On Linux:
#    sudo cp orbis.conf /etc/nginx/sites-available
#    sudo ln -s /etc/nginx/sites-available/orbis.conf /etc/nginx/sites-enabled/orbis.conf
# On macOs:
#    cp orbis.conf $(brew --prefix nginx)/servers/orbis.conf
#    sudo mkdir -p /var/log/nginx
#    sudo chown $(whoami):staff /var/log/nginx
# sudo nginx -t
# sudo nginx -s reload

