#!/bin/bash

echo "Checking with cppcheck ..."
cppcheck --language=c --std=c11 --enable=all --check-level=exhaustive \
    --inline-suppr --suppress=missingIncludeSystem --suppress=checkersReport \
    -I include -I /usr/local/include/orbis .
echo
echo "Checking with clang ..."
clang --analyze -Xanalyzer -analyzer-output=text -Iinclude src/*.c

