server {
    listen       8000;
    server_name  localhost;

    root  /Users/david/src/orbis/server/public;

    location / {
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-cache";
    }

    location /api/ {
        proxy_pass         http://127.0.0.1:8001;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
    }

    location /svc/ {
        proxy_pass         http://127.0.0.1:8002;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
    }

    location /files/ {
        auth_request /auth;
        alias /Users/david/src/orbis/server/private/;
        add_header Cache-Control "no-store";
        etag off;
    }

    location = /auth {
        internal;
        proxy_pass         http://127.0.0.1:8001/api/auth;
        proxy_set_header   Host $host;
        proxy_set_header   Cookie $http_cookie;
        proxy_pass_request_body off;
        proxy_set_header   Content-Length "";
    }
}

# nginx -s reload
