#!/bin/bash

source "$(dirname -- "${BASH_SOURCE[0]}")/.env"

payload=$(cat << 'EOF'
SELECT TRUE WHERE assert(CAST(@a AS INTEGER) > CAST(@b AS INTEGER), 'a must be greater than b') IS NULL;
EOF
)

# If you don't want to  return a value (i.e. checking before a statement) simply use:
# SELECT assert(CAST(@a AS INTEGER) > CAST(@b AS INTEGER), 'a must be greater than b');

curl -s -c "$BASE_DIR/cookies" -b "$BASE_DIR/cookies" "http://$SERVER_HOST/api/exec?a=1&b=1" \
     -H "Content-Type: application/sql" \
     -d "$payload" | jq -M

