#!/bin/bash

source "$(dirname -- "${BASH_SOURCE[0]}")/.env"

payload=$(cat << 'EOF'
SELECT json_group_array(json_array(id, name, email))
FROM users;
EOF
)

curl -s -c "$COOKIES_DIR/cookies" -b "$COOKIES_DIR/cookies" "http://$HOST/api/exec" \
     -H "Content-Type: application/sql" \
     -d "$payload" | jq -M

