#!/bin/bash

cd "$(dirname -- "${BASH_SOURCE[0]}")/.." || exit 1

#if [ -f service.py ]; then
#    python3 service.py &
#    SERVICE_PID=$!
#fi

./server

#[ -n "$SERVICE_PID" ] && kill "$SERVICE_PID"

