#!/bin/bash

cd "$(dirname -- "${BASH_SOURCE[0]}")/.." || exit 1

SERVICE_ACTIVE=false

if [ "$SERVICE_ACTIVE" = true ]; then
    python3 service.py &
    SERVICE_PID=$!
    ./server
    kill "$SERVICE_PID"
else
    ./server
fi

