#!/bin/bash

source "$(dirname -- "${BASH_SOURCE[0]}")/.env"
cd "$BASE_DIR" || exit 1

SERVICE_ACTIVE=false

if [ "$SERVICE_ACTIVE" = true ]; then
    python3 service.py $SERVICE_PORT "http://$SERVER_HOST" &
    SERVICE_PID=$!
fi

./server $SERVER_PORT

[ -n "$SERVICE_PID" ] && kill "$SERVICE_PID"

